exp:
  expname: CCTA
  expdir: ./logs/
  dataconfig: ./data/config.yml
network:
  net_type: mlp
  num_layers: 8
  hidden_dim: 256
  skips: [4]
  out_dim: 1
  last_activation: sigmoid
  bound: 0.3
  use_gradient_checkpointing: true  # Enable gradient checkpointing for memory efficiency
encoder:
  encoding: hashgrid
  input_dim: 3
  num_levels: 16
  level_dim: 2
  base_resolution: 16
  log2_hashmap_size: 19
render:
  n_fine: 0
  netchunk: 262144  # Reduced from 699060 for better memory management (128^3 / 8)
train:
  epoch: 5000
  lrate: 0.0001
  lrate_gamma: 0.1
  lrate_step: 5000
  resume: False
  mixed_precision: true  # Enable mixed precision training
  gradient_accumulation_steps: 1  # Can be increased if needed
  weight_decay: 1e-6  # Add weight decay for regularization
  memory_efficient_eval: true  # Use memory-efficient evaluation
log:
  i_eval: 100
  i_save: 300
